"""
train_fuzzy.py
===============
Replaces train_svm.py entirely.

Instead of machine-learning training, this script:
  1. Loads dataset_v3.csv (generated by augment_dataset.py)
     OR falls back to dataset_v2.csv if v3 is not yet generated.
  2. Runs the expert Fuzzy Logic engine on every row.
  3. Evaluates accuracy, precision, recall, F1 against ground truth labels.
  4. Saves evaluation report + the fuzzy engine config as fuzzy_model.pkl
     (so live_predictor_fuzzy.py can load it without re-importing this file).

Why Fuzzy Logic vs SVM?
  - SVM = black-box, needs labelled data, can overfit small datasets.
  - Fuzzy = fully interpretable, no training required, rules are derived from
    clinical research on EAR/MAR fatigue thresholds.
  - Both produce binary Awake/Tired labels — same live interface.
"""

import os
import pandas as pd
import numpy as np
import joblib
from sklearn.metrics import (accuracy_score, classification_report,
                              confusion_matrix)
from fuzzy_engine import FuzzyFatigueEngine

def compute_optimal_threshold(fatigue_indices, true_labels):
    """Find the fatigue index threshold that yields highest accuracy.
    Returns the threshold value.
    """
    best_thr = 0.0
    best_acc = 0.0
    # Evaluate each unique fatigue index as candidate threshold
    for thr in np.unique(fatigue_indices):
        preds = (fatigue_indices > thr).astype(int)
        acc = (preds == true_labels).mean()
        if acc > best_acc:
            best_acc = acc
            best_thr = thr
    return best_thr

print("=" * 65)
print("  LCDT — Fuzzy Logic Fatigue Model Evaluation")
print("  (Replaces: train_svm.py + SVC + GridSearchCV)")
print("=" * 65)

# ── 1. Load Dataset ────────────────────────────────────────────────────────
CSV_V3 = "dataset_v3.csv"
CSV_V2 = "dataset_v2.csv"

if os.path.exists(CSV_V3):
    csv_path = CSV_V3
    print(f"\n[DATA] Loading {CSV_V3} (augmented dataset)...")
elif os.path.exists(CSV_V2):
    csv_path = CSV_V2
    print(f"\n[DATA] dataset_v3.csv not found. Falling back to {CSV_V2}...")
    print("       Run augment_dataset.py first to generate the full 10k dataset.")
else:
    print("ERROR: No dataset found. Run augment_dataset.py first.")
    exit(1)

df = pd.read_csv(csv_path).dropna()
print(f"[DATA] Loaded {len(df)} rows.")
print(f"       Label distribution: {df['Label'].value_counts().to_dict()}")

# ── 2. Add EAR_MA if missing ───────────────────────────────────────────────
if "EAR_MA" not in df.columns:
    df["EAR_MA"] = df["EAR"].rolling(window=10, min_periods=1).mean()

# ── 3. Run Fuzzy Inference on All Rows ─────────────────────────────────────
print("\n[FUZZY] Running inference on all rows...")
engine = FuzzyFatigueEngine()

fatigue_indices = []
predictions     = []

for i, row in df.iterrows():
    result = engine.predict(
        ear    = float(row["EAR"]),
        mar    = float(row["MAR"]),
        pitch  = float(row["Pitch"]),
        ear_ma = float(row.get("EAR_MA", row["EAR"]))
    )
    fatigue_indices.append(result["fatigue_index"])
    predictions.append(result["label"])

    if (i + 1) % 1000 == 0:
        print(f"  Processed {i+1} / {len(df)} rows...")

df["Fuzzy_Index"]  = fatigue_indices
df["Fuzzy_Pred"]   = predictions

# ── 4. Evaluate ────────────────────────────────────────────────────────────
y_true = df["Label"].astype(int).values
y_pred = np.array(predictions)

accuracy = accuracy_score(y_true, y_pred)
cm       = confusion_matrix(y_true, y_pred)

print("\n" + "=" * 65)
print("  EVALUATION RESULTS")
print("=" * 65)
print(f"\n  Dataset  : {csv_path}")
print(f"  Total rows: {len(df)}")
print(f"\n  Accuracy : {accuracy * 100:.2f}%")
print(f"\n  Confusion Matrix:")
print(f"               Pred 0   Pred 1")
print(f"  Actual 0:  {cm[0][0]:>7}  {cm[0][1]:>7}")
print(f"  Actual 1:  {cm[1][0]:>7}  {cm[1][1]:>7}")
print(f"\n  Detailed Report:")
print(classification_report(y_true, y_pred,
                             target_names=["Awake (0)", "Tired (1)"]))

# Fatigue Index statistics
print(f"  Fatigue Index Statistics:")
print(f"    Mean  = {np.mean(fatigue_indices):.2f}")
print(f"    Std   = {np.std(fatigue_indices):.2f}")
print(f"    Min   = {np.min(fatigue_indices):.2f}")
print(f"    Max   = {np.max(fatigue_indices):.2f}")

# ── 5. Save the Fuzzy Engine (as pkl for live predictor) ───────────────────
MODEL_FILE = "fuzzy_model.pkl"
joblib.dump(engine, MODEL_FILE)
print(f"\n[SAVE] Fuzzy engine saved → {MODEL_FILE}")

# Also save evaluation summary
summary = {
    "model_type":     "FuzzyLogic_Mamdani",
    "dataset":        csv_path,
    "total_rows":     int(len(df)),
    "accuracy":       round(float(accuracy), 4),
    "threshold":      engine.THRESHOLD,
    "features_used":  ["EAR", "MAR", "Pitch", "EAR_MA"],
    "n_rules":        19,
    "defuzzification":"Centroid (CoG)",
}
import json

# UPDATED: Writing the accuracy and summary results to fuzzysummary.json
with open("fuzzysummary.json", "w") as f:
    json.dump(summary, f, indent=2)
print(f"[SAVE] Evaluation summary → fuzzysummary.json")

print("\n" + "=" * 65)
print("  SUCCESS! Fuzzy Logic model ready.")
print("  Next step: run  live_predictor_fuzzy.py")
print("=" * 65)
